import type { ThemePreset } from './presets.js'

/**
 * Extended color themes
 * These themes provide additional color options beyond the default themes
 */
export const extendedThemes: ThemePreset[] = [
  {
    name: 'cyberpunk',
    label: 'Cyberpunk Neon',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(320, 25%, 65%)',
        background: 'hsl(180, 2%, 98%)',
        accent: 'hsl(290, 22%, 75%)',
      },
    },
    lightMode: {
      background: '#ebfdf9',
      foreground: '#12051a',
      card: '#ddf9f2',
      cardForeground: '#12051a',
      popover: '#ddf9f2',
      popoverForeground: '#12051a',
      primary: '#ce47eb',
      primaryForeground: '#fcf6fd',
      secondary: '#d7dbff',
      secondaryForeground: '#08071f',
      muted: '#d7e9e5',
      mutedForeground: '#6c5b79',
      accent: '#b08dff',
      accentForeground: '#f8f7ff',
      destructive: '#f0004d',
      destructiveForeground: '#fff6f6',
      border: '#bce1d8',
      input: '#bce1d8',
      ring: '#ce47eb',
    },
    darkMode: {
      background: '#07000f',
      foreground: '#fee4ff',
      card: '#0c0016',
      cardForeground: '#fee4ff',
      popover: '#0c0016',
      popoverForeground: '#fee4ff',
      primary: '#f75cff',
      primaryForeground: '#09000c',
      secondary: '#110e39',
      secondaryForeground: '#e7ecff',
      muted: '#1a0825',
      mutedForeground: '#a57fae',
      accent: '#9463ff',
      accentForeground: '#040112',
      destructive: '#ff0063',
      destructiveForeground: '#0f0001',
      border: '#2d143e',
      input: '#2d143e',
      ring: '#f75cff',
    },
  },
  {
    name: 'minimal',
    label: 'Minimal Clean',
    borderRadius: 'none',
    preview: {
      colors: {
        primary: 'hsl(0, 0%, 12%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 96%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#060606',
      card: '#ffffff',
      cardForeground: '#060606',
      popover: '#ffffff',
      popoverForeground: '#060606',
      primary: '#060606',
      primaryForeground: '#ffffff',
      secondary: '#f8f8f8',
      secondaryForeground: '#060606',
      muted: '#f8f8f8',
      mutedForeground: '#717171',
      accent: '#f2f2f2',
      accentForeground: '#060606',
      destructive: '#d40924',
      destructiveForeground: '#ffffff',
      border: '#ebebeb',
      input: '#ebebeb',
      ring: '#060606',
    },
    darkMode: {
      background: '#060606',
      foreground: '#f8f8f8',
      card: '#0d0d0d',
      cardForeground: '#f8f8f8',
      popover: '#0d0d0d',
      popoverForeground: '#f8f8f8',
      primary: '#f8f8f8',
      primaryForeground: '#060606',
      secondary: '#1b1b1b',
      secondaryForeground: '#f8f8f8',
      muted: '#1b1b1b',
      mutedForeground: '#8f8f8f',
      accent: '#292929',
      accentForeground: '#f8f8f8',
      destructive: '#ff2335',
      destructiveForeground: '#f8f8f8',
      border: '#242424',
      input: '#242424',
      ring: '#cecece',
    },
  },
  {
    name: 'retro',
    label: 'Retro Vintage',
    borderRadius: 'small',
    preview: {
      colors: {
        primary: 'hsl(35, 18%, 55%)',
        background: 'hsl(80, 3%, 96%)',
        accent: 'hsl(50, 16%, 68%)',
      },
    },
    lightMode: {
      background: '#fdf0dc',
      foreground: '#35180e',
      card: '#fbe8ce',
      cardForeground: '#35180e',
      popover: '#fbe8ce',
      popoverForeground: '#35180e',
      primary: '#c43b15',
      primaryForeground: '#ffede9',
      secondary: '#f2d1ad',
      secondaryForeground: '#311d03',
      muted: '#ecdcc1',
      mutedForeground: '#844d3a',
      accent: '#e4762c',
      accentForeground: '#feeee6',
      destructive: '#c11435',
      destructiveForeground: '#ffedec',
      border: '#e1caaa',
      input: '#e1caaa',
      ring: '#c43b15',
    },
    darkMode: {
      background: '#200b04',
      foreground: '#f3e2c7',
      card: '#2d1107',
      cardForeground: '#f3e2c7',
      popover: '#2d1107',
      popoverForeground: '#f3e2c7',
      primary: '#ff6a43',
      primaryForeground: '#200a05',
      secondary: '#462400',
      secondaryForeground: '#f6e1c9',
      muted: '#3c180b',
      mutedForeground: '#b2935e',
      accent: '#d05500',
      accentForeground: '#1f0b02',
      destructive: '#ff4a5d',
      destructiveForeground: '#20090a',
      border: '#4c271a',
      input: '#4c271a',
      ring: '#ff6a43',
    },
  },
  {
    name: 'brutal',
    label: 'Brutal',
    borderRadius: 'none',
    preview: {
      colors: {
        primary: 'hsl(0, 0%, 0%)',
        background: 'hsl(0, 0%, 99%)',
        accent: 'hsl(0, 0%, 85%)',
      },
    },
    lightMode: {
      background: '#fcfcfc',
      foreground: '#000000',
      card: '#fcfcfc',
      cardForeground: '#000000',
      popover: '#fcfcfc',
      popoverForeground: '#000000',
      primary: '#000000',
      primaryForeground: '#fcfcfc',
      secondary: '#cecece',
      secondaryForeground: '#000000',
      muted: '#dedede',
      mutedForeground: '#484848',
      accent: '#cecece',
      accentForeground: '#000000',
      destructive: '#df000d',
      destructiveForeground: '#fcfcfc',
      border: '#000000',
      input: '#000000',
      ring: '#000000',
    },
    darkMode: {
      background: '#030303',
      foreground: '#fcfcfc',
      card: '#030303',
      cardForeground: '#fcfcfc',
      popover: '#030303',
      popoverForeground: '#fcfcfc',
      primary: '#fcfcfc',
      primaryForeground: '#030303',
      secondary: '#222222',
      secondaryForeground: '#fcfcfc',
      muted: '#161616',
      mutedForeground: '#9e9e9e',
      accent: '#222222',
      accentForeground: '#fcfcfc',
      destructive: '#ff0022',
      destructiveForeground: '#030303',
      border: '#fcfcfc',
      input: '#fcfcfc',
      ring: '#fcfcfc',
    },
  },
  {
    name: 'pastel',
    label: 'Pastel Soft',
    borderRadius: 'xl',
    preview: {
      colors: {
        primary: 'hsl(270, 12%, 70%)',
        background: 'hsl(250, 1%, 98%)',
        accent: 'hsl(300, 8%, 85%)',
      },
    },
    lightMode: {
      background: '#f4f9ff',
      foreground: '#1e2f41',
      card: '#e6f4fe',
      cardForeground: '#1e2f41',
      popover: '#e6f4fe',
      popoverForeground: '#1e2f41',
      primary: '#819ae9',
      primaryForeground: '#f6f8ff',
      secondary: '#afebee',
      secondaryForeground: '#113436',
      muted: '#d7ebfa',
      mutedForeground: '#577594',
      accent: '#d5c2fb',
      accentForeground: '#31293f',
      destructive: '#db6468',
      destructiveForeground: '#fff6f6',
      border: '#bbddf6',
      input: '#bbddf6',
      ring: '#819ae9',
    },
    darkMode: {
      background: '#071727',
      foreground: '#e9eefc',
      card: '#042234',
      cardForeground: '#e9eefc',
      popover: '#042234',
      popoverForeground: '#e9eefc',
      primary: '#8ca8ff',
      primaryForeground: '#0f1528',
      secondary: '#00464b',
      secondaryForeground: '#e0f3f4',
      muted: '#042c43',
      mutedForeground: '#8b9cd1',
      accent: '#6c5594',
      accentForeground: '#f0ecfa',
      destructive: '#fa676e',
      destructiveForeground: '#250e0e',
      border: '#10364e',
      input: '#10364e',
      ring: '#8ca8ff',
    },
  },
  {
    name: 'ocean',
    label: 'Ocean Deep',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(230, 18%, 55%)',
        background: 'hsl(220, 2%, 97%)',
        accent: 'hsl(190, 15%, 68%)',
      },
    },
    lightMode: {
      background: '#e7f9ff',
      foreground: '#00202e',
      card: '#d9f4fb',
      cardForeground: '#00202e',
      popover: '#d9f4fb',
      popoverForeground: '#00202e',
      primary: '#007fc5',
      primaryForeground: '#e8f8ff',
      secondary: '#a9e4e7',
      secondaryForeground: '#002225',
      muted: '#c4e9f2',
      mutedForeground: '#1f6e83',
      accent: '#00b4ad',
      accentForeground: '#e7faf8',
      destructive: '#df202e',
      destructiveForeground: '#fff0ee',
      border: '#a9d7e2',
      input: '#a9d7e2',
      ring: '#007fc5',
    },
    darkMode: {
      background: '#000e17',
      foreground: '#c8ebf7',
      card: '#001922',
      cardForeground: '#c8ebf7',
      popover: '#001922',
      popoverForeground: '#c8ebf7',
      primary: '#00b0ff',
      primaryForeground: '#000e19',
      secondary: '#003338',
      secondaryForeground: '#c7edef',
      muted: '#002631',
      mutedForeground: '#5ba4ba',
      accent: '#009791',
      accentForeground: '#c7eeea',
      destructive: '#ff3d44',
      destructiveForeground: '#190404',
      border: '#003540',
      input: '#003540',
      ring: '#00b0ff',
    },
  },
  {
    name: 'forest',
    label: 'Forest Green',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(145, 16%, 52%)',
        background: 'hsl(145, 2%, 97%)',
        accent: 'hsl(155, 14%, 65%)',
      },
    },
    lightMode: {
      background: '#edf9ed',
      foreground: '#011d04',
      card: '#e4f4e1',
      cardForeground: '#011d04',
      popover: '#e4f4e1',
      popoverForeground: '#011d04',
      primary: '#097f23',
      primaryForeground: '#edf9ed',
      secondary: '#cddfbc',
      secondaryForeground: '#0c1b00',
      muted: '#d7e7d4',
      mutedForeground: '#3f6a41',
      accent: '#33a868',
      accentForeground: '#ebf9ef',
      destructive: '#df202e',
      destructiveForeground: '#fff0ee',
      border: '#c0d5bc',
      input: '#c0d5bc',
      ring: '#097f23',
    },
    darkMode: {
      background: '#031203',
      foreground: '#d9ead9',
      card: '#081b05',
      cardForeground: '#d9ead9',
      popover: '#081b05',
      popoverForeground: '#d9ead9',
      primary: '#3db44a',
      primaryForeground: '#031203',
      secondary: '#223409',
      secondaryForeground: '#dee9d4',
      muted: '#14270f',
      mutedForeground: '#7da47e',
      accent: '#00944d',
      accentForeground: '#d6ebdc',
      destructive: '#ff3d44',
      destructiveForeground: '#1b0605',
      border: '#213a1c',
      input: '#213a1c',
      ring: '#3db44a',
    },
  },
  {
    name: 'sunset',
    label: 'Sunset Warm',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(35, 20%, 60%)',
        background: 'hsl(50, 3%, 97%)',
        accent: 'hsl(20, 18%, 68%)',
      },
    },
    lightMode: {
      background: '#fff0e4',
      foreground: '#391609',
      card: '#ffe7d9',
      cardForeground: '#391609',
      popover: '#ffe7d9',
      popoverForeground: '#391609',
      primary: '#dd4115',
      primaryForeground: '#fff1ec',
      secondary: '#ffcaa5',
      secondaryForeground: '#371801',
      muted: '#ffd8c6',
      mutedForeground: '#8e503a',
      accent: '#f36069',
      accentForeground: '#fff0ef',
      destructive: '#e5004a',
      destructiveForeground: '#fff0f1',
      border: '#f4c5b1',
      input: '#f4c5b1',
      ring: '#dd4115',
    },
    darkMode: {
      background: '#230802',
      foreground: '#ffe4d4',
      card: '#300f01',
      cardForeground: '#ffe4d4',
      popover: '#300f01',
      popoverForeground: '#ffe4d4',
      primary: '#ff6134',
      primaryForeground: '#230703',
      secondary: '#572000',
      secondaryForeground: '#ffe5d2',
      muted: '#3e1602',
      mutedForeground: '#cc8e6b',
      accent: '#e54151',
      accentForeground: '#ffe1e0',
      destructive: '#ff2162',
      destructiveForeground: '#23060a',
      border: '#592810',
      input: '#592810',
      ring: '#ff6134',
    },
  },
  {
    name: 'lavender',
    label: 'Lavender Dream',
    borderRadius: 'xl',
    preview: {
      colors: {
        primary: 'hsl(295, 16%, 62%)',
        background: 'hsl(295, 2%, 98%)',
        accent: 'hsl(310, 14%, 72%)',
      },
    },
    lightMode: {
      background: '#f9f6ff',
      foreground: '#231c37',
      card: '#f1efff',
      cardForeground: '#231c37',
      popover: '#f1efff',
      popoverForeground: '#231c37',
      primary: '#8f6edb',
      primaryForeground: '#f9f7ff',
      secondary: '#d5daff',
      secondaryForeground: '#1d1e39',
      muted: '#e7e4ff',
      mutedForeground: '#6c5f92',
      accent: '#bf8ae6',
      accentForeground: '#faf7fe',
      destructive: '#df202e',
      destructiveForeground: '#fff6f5',
      border: '#d6d3f7',
      input: '#d6d3f7',
      ring: '#8f6edb',
    },
    darkMode: {
      background: '#110b1f',
      foreground: '#e9e4fa',
      card: '#18132d',
      cardForeground: '#e9e4fa',
      popover: '#18132d',
      popoverForeground: '#e9e4fa',
      primary: '#a883ff',
      primaryForeground: '#110b1f',
      secondary: '#272755',
      secondaryForeground: '#e3e6fc',
      muted: '#241e3f',
      mutedForeground: '#a295cb',
      accent: '#9d60c6',
      accentForeground: '#eee3f7',
      destructive: '#ff3d44',
      destructiveForeground: '#1e0707',
      border: '#332c54',
      input: '#332c54',
      ring: '#a883ff',
    },
  },
  {
    name: 'neutral',
    label: 'Neutral',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(0, 0%, 0%)',
        background: 'hsl(0, 0%, 99%)',
        accent: 'hsl(0, 0%, 94%)',
      },
    },
    lightMode: {
      background: '#fcfcfc',
      foreground: '#000000',
      card: '#fcfcfc',
      cardForeground: '#000000',
      popover: '#fcfcfc',
      popoverForeground: '#000000',
      primary: '#000000',
      primaryForeground: '#ffffff',
      secondary: '#ebebeb',
      secondaryForeground: '#000000',
      muted: '#f5f5f5',
      mutedForeground: '#525252',
      accent: '#ebebeb',
      accentForeground: '#000000',
      destructive: '#e54b4f',
      destructiveForeground: '#ffffff',
      border: '#e4e4e4',
      input: '#ebebeb',
      ring: '#000000',
    },
    darkMode: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#090909',
      cardForeground: '#ffffff',
      popover: '#121212',
      popoverForeground: '#ffffff',
      primary: '#ffffff',
      primaryForeground: '#000000',
      secondary: '#222222',
      secondaryForeground: '#ffffff',
      muted: '#1d1d1d',
      mutedForeground: '#a4a4a4',
      accent: '#333333',
      accentForeground: '#ffffff',
      destructive: '#ff5b5b',
      destructiveForeground: '#000000',
      border: '#242424',
      input: '#333333',
      ring: '#a4a4a4',
    },
  },
  {
    name: 'blue',
    label: 'Blue',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(221, 83%, 53%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 97%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#2563eb',
      primaryForeground: '#eff6ff',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      destructive: '#e7000b',
      destructiveForeground: '#f8f8f8',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#60a5fa',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      cardForeground: '#fafafa',
      popover: '#262626',
      popoverForeground: '#fafafa',
      primary: '#3b82f6',
      primaryForeground: '#eff6ff',
      secondary: '#262626',
      secondaryForeground: '#fafafa',
      muted: '#262626',
      mutedForeground: '#a1a1a1',
      accent: '#404040',
      accentForeground: '#fafafa',
      destructive: '#ff6467',
      destructiveForeground: '#f8f8f8',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#1e3a8a',
    },
  },
  {
    name: 'green',
    label: 'Green',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(85, 85%, 35%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 97%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#65a30d',
      primaryForeground: '#f7fee7',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      destructive: '#e7000b',
      destructiveForeground: '#f8f8f8',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#a3e635',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      cardForeground: '#fafafa',
      popover: '#262626',
      popoverForeground: '#fafafa',
      primary: '#84cc16',
      primaryForeground: '#f7fee7',
      secondary: '#262626',
      secondaryForeground: '#fafafa',
      muted: '#262626',
      mutedForeground: '#a1a1a1',
      accent: '#404040',
      accentForeground: '#fafafa',
      destructive: '#ff6467',
      destructiveForeground: '#f8f8f8',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#365314',
    },
  },
  {
    name: 'red',
    label: 'Red',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(0, 72%, 51%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 97%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#dc2626',
      primaryForeground: '#fef2f2',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      destructive: '#e7000b',
      destructiveForeground: '#f8f8f8',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#f87171',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      cardForeground: '#fafafa',
      popover: '#262626',
      popoverForeground: '#fafafa',
      primary: '#ef4444',
      primaryForeground: '#fef2f2',
      secondary: '#262626',
      secondaryForeground: '#fafafa',
      muted: '#262626',
      mutedForeground: '#a1a1a1',
      accent: '#404040',
      accentForeground: '#fafafa',
      destructive: '#ff6467',
      destructiveForeground: '#f8f8f8',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#7f1d1d',
    },
  },
  {
    name: 'orange',
    label: 'Orange',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(21, 90%, 48%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 97%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#ea580c',
      primaryForeground: '#fff7ed',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      destructive: '#e7000b',
      destructiveForeground: '#f8f8f8',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#fb923c',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      cardForeground: '#fafafa',
      popover: '#262626',
      popoverForeground: '#fafafa',
      primary: '#f97316',
      primaryForeground: '#fff7ed',
      secondary: '#262626',
      secondaryForeground: '#fafafa',
      muted: '#262626',
      mutedForeground: '#a1a1a1',
      accent: '#404040',
      accentForeground: '#fafafa',
      destructive: '#ff6467',
      destructiveForeground: '#f8f8f8',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#7c2d12',
    },
  },
  {
    name: 'rose',
    label: 'Rose',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(347, 77%, 50%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 97%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#e11d48',
      primaryForeground: '#fff1f2',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      destructive: '#e7000b',
      destructiveForeground: '#f8f8f8',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#fb7185',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      cardForeground: '#fafafa',
      popover: '#262626',
      popoverForeground: '#fafafa',
      primary: '#f43f5e',
      primaryForeground: '#fff1f2',
      secondary: '#262626',
      secondaryForeground: '#fafafa',
      muted: '#262626',
      mutedForeground: '#a1a1a1',
      accent: '#404040',
      accentForeground: '#fafafa',
      destructive: '#ff6467',
      destructiveForeground: '#f8f8f8',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#881337',
    },
  },
  {
    name: 'violet',
    label: 'Violet',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: 'hsl(262, 83%, 58%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 97%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#7c3aed',
      primaryForeground: '#f5f3ff',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      destructive: '#e7000b',
      destructiveForeground: '#f8f8f8',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#a78bfa',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      cardForeground: '#fafafa',
      popover: '#262626',
      popoverForeground: '#fafafa',
      primary: '#8b5cf6',
      primaryForeground: '#f5f3ff',
      secondary: '#262626',
      secondaryForeground: '#fafafa',
      muted: '#262626',
      mutedForeground: '#a1a1a1',
      accent: '#404040',
      accentForeground: '#fafafa',
      destructive: '#ff6467',
      destructiveForeground: '#f8f8f8',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#4c1d95',
    },
  },
  {
    name: 'zinc',
    label: 'Zinc',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(286.375, 1%, 14%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(286.375, 0%, 96%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0c',
      card: '#ffffff',
      cardForeground: '#0a0a0c',
      popover: '#ffffff',
      popoverForeground: '#0a0a0c',
      primary: '#0a0a0c',
      primaryForeground: '#fafafa',
      secondary: '#f2f2f3',
      secondaryForeground: '#0a0a0c',
      muted: '#f2f2f3',
      mutedForeground: '#6c6c75',
      accent: '#f2f2f3',
      accentForeground: '#0a0a0c',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#0a0a0c',
    },
    darkMode: {
      background: '#0a0a0c',
      foreground: '#fafafa',
      card: '#0a0a0c',
      cardForeground: '#fafafa',
      popover: '#0a0a0c',
      popoverForeground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#0a0a0c',
      secondary: '#1f1f26',
      secondaryForeground: '#fafafa',
      muted: '#1f1f26',
      mutedForeground: '#8b8b93',
      accent: '#1f1f26',
      accentForeground: '#fafafa',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#1f1f26',
      input: '#1f1f26',
      ring: '#ceced0',
    },
  },
  {
    name: 'slate',
    label: 'Slate',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(254.624, 1%, 15%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(254.624, 0%, 96%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#070b10',
      card: '#ffffff',
      cardForeground: '#070b10',
      popover: '#ffffff',
      popoverForeground: '#070b10',
      primary: '#070b10',
      primaryForeground: '#fafafa',
      secondary: '#f1f2f4',
      secondaryForeground: '#070b10',
      muted: '#f1f2f4',
      mutedForeground: '#656d78',
      accent: '#f1f2f4',
      accentForeground: '#070b10',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#e2e5e9',
      input: '#e2e5e9',
      ring: '#070b10',
    },
    darkMode: {
      background: '#070b10',
      foreground: '#fafafa',
      card: '#070b10',
      cardForeground: '#fafafa',
      popover: '#070b10',
      popoverForeground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#070b10',
      secondary: '#1a212b',
      secondaryForeground: '#fafafa',
      muted: '#1a212b',
      mutedForeground: '#858c96',
      accent: '#1a212b',
      accentForeground: '#fafafa',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#1a212b',
      input: '#1a212b',
      ring: '#cbced3',
    },
  },
  {
    name: 'stone',
    label: 'Stone',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(56.365, 1%, 14%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(60, 0%, 96%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0c0908',
      card: '#ffffff',
      cardForeground: '#0c0908',
      popover: '#ffffff',
      popoverForeground: '#0c0908',
      primary: '#0c0908',
      primaryForeground: '#fafafa',
      secondary: '#f3f2f1',
      secondaryForeground: '#0c0908',
      muted: '#f3f2f1',
      mutedForeground: '#726b67',
      accent: '#f3f2f1',
      accentForeground: '#0c0908',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#e7e4e2',
      input: '#e7e4e2',
      ring: '#0c0908',
    },
    darkMode: {
      background: '#0c0908',
      foreground: '#fafafa',
      card: '#0c0908',
      cardForeground: '#fafafa',
      popover: '#0c0908',
      popoverForeground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#0c0908',
      secondary: '#251f1b',
      secondaryForeground: '#fafafa',
      muted: '#251f1b',
      mutedForeground: '#908a86',
      accent: '#251f1b',
      accentForeground: '#fafafa',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#251f1b',
      input: '#251f1b',
      ring: '#d1cdcb',
    },
  },
  {
    name: 'gray',
    label: 'Gray',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: 'hsl(0, 0%, 14%)',
        background: 'hsl(0, 0%, 100%)',
        accent: 'hsl(0, 0%, 96%)',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#0a0a0a',
      primaryForeground: '#fafafa',
      secondary: '#f2f2f2',
      secondaryForeground: '#0a0a0a',
      muted: '#f2f2f2',
      mutedForeground: '#6c6c6c',
      accent: '#f2f2f2',
      accentForeground: '#0a0a0a',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#0a0a0a',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#0a0a0a',
      cardForeground: '#fafafa',
      popover: '#0a0a0a',
      popoverForeground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#0a0a0a',
      secondary: '#202020',
      secondaryForeground: '#fafafa',
      muted: '#202020',
      mutedForeground: '#8b8b8b',
      accent: '#202020',
      accentForeground: '#fafafa',
      destructive: '#e7000b',
      destructiveForeground: '#fafafa',
      border: '#202020',
      input: '#202020',
      ring: '#cecece',
    },
  },
]
