export interface ThemeTypographyPreset {
  fontFamily: string
  headingFamily: string
  baseFontSize: string
  lineHeight: string
  fontWeights: {
    light?: string
    normal?: string
    medium?: string
    semibold?: string
    bold?: string
    black?: string
  }
  letterSpacing: {
    tight?: string
    normal?: string
    wide?: string
    wider?: string
  }
}

export interface ThemePreset {
  name: string
  label: string
  borderRadius: 'none' | 'small' | 'medium' | 'large' | 'xl'
  cssFile?: string
  preview?: {
    colors: {
      primary: string
      background: string
      accent: string
    }
  }
  theme?: string
  colorMode?: 'auto' | 'light' | 'dark'
  fontScale?: 'small' | 'medium' | 'large'
  spacing?: 'small' | 'medium' | 'large'
  animationLevel?: 'low' | 'medium' | 'high'
  lightMode?: Record<string, string>
  darkMode?: Record<string, string>
  typography?: ThemeTypographyPreset
}

export const defaultThemePresets: ThemePreset[] = [
  {
    name: 'cool',
    label: 'Cool & Professional',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: '#3b82f6',
        background: '#ffffff',
        accent: '#f1f5f9',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      accent: '#f1f5f9',
      accentForeground: '#0f172a',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#3b82f6',
    },
    darkMode: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#1a1a1a',
      cardForeground: '#fafafa',
      popover: '#1a1a1a',
      popoverForeground: '#fafafa',
      primary: '#60a5fa',
      primaryForeground: '#0a0a0a',
      secondary: '#27272a',
      secondaryForeground: '#fafafa',
      muted: '#27272a',
      mutedForeground: '#a1a1aa',
      accent: '#27272a',
      accentForeground: '#fafafa',
      destructive: '#f87171',
      destructiveForeground: '#0a0a0a',
      border: '#27272a',
      input: '#27272a',
      ring: '#60a5fa',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-outfit)',
      baseFontSize: '16px',
      lineHeight: '1.6',
      fontWeights: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      letterSpacing: {
        tight: '-0.02em',
        normal: '0',
        wide: '0.02em',
      },
    },
  },
  {
    name: 'brutal',
    label: 'Modern Brutalism',
    borderRadius: 'none',
    preview: {
      colors: {
        primary: '#000000',
        background: '#ffffff',
        accent: '#ef4444',
      },
    },
    lightMode: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#ffffff',
      cardForeground: '#000000',
      popover: '#ffffff',
      popoverForeground: '#000000',
      primary: '#000000',
      primaryForeground: '#ffffff',
      secondary: '#f5f5f5',
      secondaryForeground: '#000000',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#ef4444',
      accentForeground: '#ffffff',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#000000',
      input: '#e5e5e5',
      ring: '#000000',
    },
    darkMode: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#0a0a0a',
      cardForeground: '#ffffff',
      popover: '#0a0a0a',
      popoverForeground: '#ffffff',
      primary: '#ffffff',
      primaryForeground: '#000000',
      secondary: '#262626',
      secondaryForeground: '#ffffff',
      muted: '#262626',
      mutedForeground: '#a3a3a3',
      accent: '#ef4444',
      accentForeground: '#ffffff',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#ffffff',
      input: '#262626',
      ring: '#ffffff',
    },
    typography: {
      fontFamily: 'var(--font-geist-mono)',
      headingFamily: 'var(--font-geist-mono)',
      baseFontSize: '16px',
      lineHeight: '1.5',
      fontWeights: {
        normal: '400',
        medium: '600',
        semibold: '700',
        bold: '800',
      },
      letterSpacing: {
        tight: '0',
        normal: '0.05em',
        wide: '0.1em',
      },
    },
  },
  {
    name: 'neon',
    label: 'Neon Cyberpunk',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: '#9333ea',
        background: '#0d0f1a',
        accent: '#00ffff',
      },
    },
    lightMode: {
      background: '#0d0f1a',
      foreground: '#ffffff',
      card: '#12141f',
      cardForeground: '#ffffff',
      popover: '#12141f',
      popoverForeground: '#ffffff',
      primary: '#9333ea',
      primaryForeground: '#ffffff',
      secondary: '#1a1d2e',
      secondaryForeground: '#ffffff',
      muted: '#1a1d2e',
      mutedForeground: '#b3b3cc',
      accent: '#00ffff',
      accentForeground: '#0d0f1a',
      destructive: '#ff0000',
      destructiveForeground: '#ffffff',
      border: '#2d3348',
      input: '#2d3348',
      ring: '#9333ea',
    },
    darkMode: {
      background: '#0d0f1a',
      foreground: '#ffffff',
      card: '#12141f',
      cardForeground: '#ffffff',
      popover: '#12141f',
      popoverForeground: '#ffffff',
      primary: '#9333ea',
      primaryForeground: '#ffffff',
      secondary: '#1a1d2e',
      secondaryForeground: '#ffffff',
      muted: '#1a1d2e',
      mutedForeground: '#b3b3cc',
      accent: '#00ffff',
      accentForeground: '#0d0f1a',
      destructive: '#ff0000',
      destructiveForeground: '#0d0f1a',
      border: '#2d3348',
      input: '#2d3348',
      ring: '#9333ea',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-geist-mono)',
      baseFontSize: '16px',
      lineHeight: '1.7',
      fontWeights: {
        normal: '400',
        medium: '500',
        semibold: '700',
        bold: '900',
      },
      letterSpacing: {
        tight: '0',
        normal: '0.05em',
        wide: '0.15em',
      },
    },
  },
  {
    name: 'solar',
    label: 'Solar',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: '#c85a19',
        background: '#fffbf5',
        accent: '#ffcc00',
      },
    },
    lightMode: {
      background: '#fffbf5',
      foreground: '#2d1a09',
      card: '#ffffff',
      cardForeground: '#2d1a09',
      popover: '#ffffff',
      popoverForeground: '#2d1a09',
      primary: '#c85a19',
      primaryForeground: '#ffffff',
      secondary: '#fff7e6',
      secondaryForeground: '#2d1a09',
      muted: '#f5ebe0',
      mutedForeground: '#665544',
      accent: '#ffcc00',
      accentForeground: '#2d1a09',
      destructive: '#e34850',
      destructiveForeground: '#ffffff',
      border: '#e8d4c4',
      input: '#e8d4c4',
      ring: '#c85a19',
    },
    darkMode: {
      background: '#1f1610',
      foreground: '#f0dcc7',
      card: '#271c15',
      cardForeground: '#f0dcc7',
      popover: '#271c15',
      popoverForeground: '#f0dcc7',
      primary: '#e37a3d',
      primaryForeground: '#ffffff',
      secondary: '#3d2f26',
      secondaryForeground: '#f0dcc7',
      muted: '#3d2f26',
      mutedForeground: '#ccb8a6',
      accent: '#ffd633',
      accentForeground: '#1f1610',
      destructive: '#993438',
      destructiveForeground: '#ffffff',
      border: '#453828',
      input: '#453828',
      ring: '#e37a3d',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-outfit)',
      baseFontSize: '16px',
      lineHeight: '1.6',
      fontWeights: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      letterSpacing: {
        tight: '-0.01em',
        normal: '0',
        wide: '0.025em',
      },
    },
  },
  {
    name: 'dealership',
    label: 'Dealership',
    borderRadius: 'medium',
    preview: {
      colors: {
        primary: '#1a2f50',
        background: '#f9fafb',
        accent: '#3b9ad6',
      },
    },
    lightMode: {
      background: '#f9fafb',
      foreground: '#1f2937',
      card: '#ffffff',
      cardForeground: '#1f2937',
      popover: '#ffffff',
      popoverForeground: '#1f2937',
      primary: '#1a2f50',
      primaryForeground: '#ffffff',
      secondary: '#e6ebf0',
      secondaryForeground: '#1f2937',
      muted: '#e6ebf0',
      mutedForeground: '#6b7280',
      accent: '#3b9ad6',
      accentForeground: '#ffffff',
      destructive: '#bc3535',
      destructiveForeground: '#ffffff',
      border: '#d1d5db',
      input: '#d1d5db',
      ring: '#1a2f50',
    },
    darkMode: {
      background: '#111827',
      foreground: '#f3f4f6',
      card: '#1f2937',
      cardForeground: '#f3f4f6',
      popover: '#1f2937',
      popoverForeground: '#f3f4f6',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#374151',
      secondaryForeground: '#f3f4f6',
      muted: '#374151',
      mutedForeground: '#9ca3af',
      accent: '#60a5fa',
      accentForeground: '#111827',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#4b5563',
      input: '#4b5563',
      ring: '#3b82f6',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-outfit)',
      baseFontSize: '16px',
      lineHeight: '1.6',
      fontWeights: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      letterSpacing: {
        tight: '-0.01em',
        normal: '0.01em',
        wide: '0.05em',
      },
    },
  },
  {
    name: 'real-estate',
    label: 'Real Estate Blue',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: '#1e40af',
        background: '#fafbff',
        accent: '#3b9ad6',
      },
    },
    lightMode: {
      background: '#fafbff',
      foreground: '#1e293b',
      card: '#ffffff',
      cardForeground: '#1e293b',
      popover: '#ffffff',
      popoverForeground: '#1e293b',
      primary: '#1e40af',
      primaryForeground: '#ffffff',
      secondary: '#e0ecff',
      secondaryForeground: '#1e293b',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      accent: '#3b9ad6',
      accentForeground: '#ffffff',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#cbd5e1',
      input: '#f1f5f9',
      ring: '#1e40af',
    },
    darkMode: {
      background: '#0f172a',
      foreground: '#f1f5f9',
      card: '#1e293b',
      cardForeground: '#f1f5f9',
      popover: '#1e293b',
      popoverForeground: '#f1f5f9',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#334155',
      secondaryForeground: '#f1f5f9',
      muted: '#334155',
      mutedForeground: '#94a3b8',
      accent: '#60a5fa',
      accentForeground: '#0f172a',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#475569',
      input: '#334155',
      ring: '#3b82f6',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-outfit)',
      baseFontSize: '16px',
      lineHeight: '1.75',
      fontWeights: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        black: '900',
      },
      letterSpacing: {
        tight: '-0.02em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
      },
    },
  },
  {
    name: 'real-estate-gold',
    label: 'Real Estate Gold',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: '#b8860b',
        background: '#fffbf0',
        accent: '#f5d547',
      },
    },
    lightMode: {
      background: '#fffbf0',
      foreground: '#302618',
      card: '#ffffff',
      cardForeground: '#302618',
      popover: '#ffffff',
      popoverForeground: '#302618',
      primary: '#b8860b',
      primaryForeground: '#fffbf0',
      secondary: '#f7eed6',
      secondaryForeground: '#302618',
      muted: '#f3e9d8',
      mutedForeground: '#6d5d47',
      accent: '#f5d547',
      accentForeground: '#302618',
      destructive: '#dc2f2f',
      destructiveForeground: '#ffffff',
      border: '#e5d9c0',
      input: '#f3e9d8',
      ring: '#b8860b',
    },
    darkMode: {
      background: '#1a1510',
      foreground: '#f5f0e6',
      card: '#262014',
      cardForeground: '#f5f0e6',
      popover: '#262014',
      popoverForeground: '#f5f0e6',
      primary: '#daa520',
      primaryForeground: '#1a1510',
      secondary: '#3d3426',
      secondaryForeground: '#f5f0e6',
      muted: '#3d3426',
      mutedForeground: '#b8a68f',
      accent: '#ffd700',
      accentForeground: '#1a1510',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#554729',
      input: '#3d3426',
      ring: '#daa520',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-outfit)',
      baseFontSize: '16px',
      lineHeight: '1.75',
      fontWeights: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        black: '900',
      },
      letterSpacing: {
        tight: '-0.02em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
      },
    },
  },
  {
    name: 'real-estate-neutral',
    label: 'Real Estate Neutral',
    borderRadius: 'large',
    preview: {
      colors: {
        primary: '#57534e',
        background: '#fafaf9',
        accent: '#78716c',
      },
    },
    lightMode: {
      background: '#fafaf9',
      foreground: '#292524',
      card: '#ffffff',
      cardForeground: '#292524',
      popover: '#ffffff',
      popoverForeground: '#292524',
      primary: '#57534e',
      primaryForeground: '#ffffff',
      secondary: '#e7e5e4',
      secondaryForeground: '#292524',
      muted: '#f5f5f4',
      mutedForeground: '#78716c',
      accent: '#78716c',
      accentForeground: '#ffffff',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#d6d3d1',
      input: '#f5f5f4',
      ring: '#57534e',
    },
    darkMode: {
      background: '#1c1917',
      foreground: '#fafaf9',
      card: '#292524',
      cardForeground: '#fafaf9',
      popover: '#292524',
      popoverForeground: '#fafaf9',
      primary: '#78716c',
      primaryForeground: '#ffffff',
      secondary: '#44403c',
      secondaryForeground: '#fafaf9',
      muted: '#44403c',
      mutedForeground: '#a8a29e',
      accent: '#a8a29e',
      accentForeground: '#1c1917',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#57534e',
      input: '#44403c',
      ring: '#78716c',
    },
    typography: {
      fontFamily: 'var(--font-geist-sans)',
      headingFamily: 'var(--font-outfit)',
      baseFontSize: '16px',
      lineHeight: '1.75',
      fontWeights: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        black: '900',
      },
      letterSpacing: {
        tight: '-0.02em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
      },
    },
  },
]
