name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release (relative path without leading slash)'
        required: true
        default: 'packages/theme-management'
      bump:
        description: 'version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: pnpm/action-setup@v2
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@9.4.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run standard-version (bump changelog)
        working-directory: ${{ inputs.package }}
        run: pnpm -w -F @kilivi/payloadcms-theme-management run release -- -r ${GITHUB_REF_NAME:-HEAD} --release-as ${{ inputs.bump }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore(release): bump version and changelog
          committer: GitHub <noreply@github.com>
          title: chore(release): bump version and changelog
          body: This PR contains a version bump and changelog generated by standard-version.
          branch: chore/release-${{ github.sha }}
